project 'FileSystemDemo.xcodeproj'

# nhibit_all_warnings!
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :osx, '10.11'

target 'FileSystemDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FileSystemDemo
  
  pod 'ReactiveObjC'
  
  pod 'AFNetworking', '2.0'

#   target 'FileSystemDemoTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# 
#   target 'FileSystemDemoUITests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

end
